from aiogram.dispatcher.filters.state import StatesGroup, State

class Fonts(StatesGroup):
    font_1 = State()
    font_2 = State()
    font_3 = State()
    font_4 = State()
    font_5 = State()
    font_6 = State()
    font_7 = State()
    font_8 = State()
    font_9 = State()
    font_10 = State()
    font_11 = State()
    font_12 = State()
    font_13 = State()
    font_14 = State()
    font_15 = State()
    font_16 = State()
    font_17 = State()
    font_18 = State()
    font_19 = State()
    font_20 = State()
    font_21 = State()
    font_22 = State()
    font_23 = State()
    font_24 = State()
    font_25 = State()
    font_26 = State()
    font_27 = State()
    font_28 = State()
    font_29 = State()